### ISSUE TITLE
PA Review Search functionality

### ISSUE THREAD

**Issue by AAlfarho** [AAlfarho/axo-music#40]
Search for users and songs.
Searching for a song allows us to add songs to our playlists, reusing previous SongIndexContainer.
Searching for a user will allow us to visit user's profile.

**Comment by AAlfarho** [comment]
Will push new set of users to the site.

**Comment by AAlfarho** [comment]
New seed live.

**Comment by niartenyaw** [comment]
Looks great!

+ Something I just noticed with your button changes, the `Log In` button at `/login` isn't updated
+ Make the selection area to switch between `Songs` and `Users` wider, maybe fill the entire width
+ I think the add to playlist button should be more prominent since you can't click the song to start playing it yet. Along with this, the `+`, `-`, and `time` could use some spacing between them on the playlist view

**Comment by AAlfarho** [comment]
Thanks for the feedback.
+ Log In issue was due to input fields not being set in my reset.css to inherit the fonts. **FIXED**
+ Area selection for both Songs and Users is set to full width. **FIXED**

**Comment by AAlfarho** [comment]
Update version with updated styles for the  **+** **-** buttons.

**Comment by AAlfarho** [comment]
Minor updates to the spacing of the buttons were pushed

**Comment by niartenyaw** [comment]
👍
